# This is a basic workflow to help you get started with Actions

name: TestInstall

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  issues:
    - name: TODO to Issue
      uses: alstr/todo-to-issue-action@v4.3

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install requiemnts
      run: sudo apt-get install -y zsh tmux python3

    # Runs a set of commands using the runners shell
    - name: install submodules
      run: git submodule update --init --recursive

    - name: run zsh
      run: zsh
